/**
 * `docs/delivery-matrix.html`, generated from `lib/matrix`, never typed.
 *
 * The page was typed by hand once, and by 2026-10-08 it said "85 of 93
 * processes built" while the matrix held 105 rows. A page describing what
 * is true is wrong within a month; this is the same page as a function of
 * the matrix, so it is wrong for exactly as long as nobody runs
 * `npm run matrix` — and `__tests__/invariants/map.test.ts` fails the
 * commit where that happens.
 *
 * Deterministic on purpose: no date, no machine, no order but the
 * matrix's own, so a fresh generation on any computer is byte-for-byte
 * the committed file.
 */

import { MATRIX, coverage, type Status } from '@/lib/matrix'
import { DOMAINS } from '@/lib/domains'
import { STATUS } from '@/lib/chart-colors'

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

const WORD: Record<Status, string> = {
  BUILT: 'Built', PARTIAL: 'Partial', SPEC: 'Written down, nothing coded', NONE: 'Not started',
}
const COLOR: Record<Status, string> = {
  BUILT: STATUS.good, PARTIAL: STATUS.warning, SPEC: STATUS.neutral, NONE: STATUS.serious,
}

const list = (xs: string[], none: string) =>
  xs.length === 0 ? `<span class="none">${none}</span>` : `<ul>${xs.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>`

export function deliveryMatrixHtml(): string {
  const c = coverage()
  const agentOf = new Map(DOMAINS.map((d) => [d.key, d.agent]))
  const out: string[] = []

  out.push(`<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Delivery matrix</title>
<!-- Generated by scripts/delivery-matrix.ts from src/lib/matrix.ts. Do not edit: run npm run matrix. -->
<style>
  body { background: #F0EEE6; color: #1F1E1D; font: 14px/1.5 Inter, -apple-system, system-ui, sans-serif; margin: 0; }
  .wrap { max-width: 1180px; margin: 0 auto; padding: 40px 24px 80px; }
  h1, h2, h3 { font-family: "Iowan Old Style", Palatino, Georgia, serif; font-weight: 400; letter-spacing: -.02em; }
  h1 { font-size: 40px; margin: 0 0 8px; }
  h2 { font-size: 26px; margin: 40px 0 4px; }
  h3 { font-size: 19px; margin: 24px 0 8px; }
  .muted { color: #6B6862; }
  .eyebrow { font-size: 10px; text-transform: uppercase; letter-spacing: .12em; color: #9C9891; font-weight: 600; }
  table { width: 100%; border-collapse: collapse; background: #FBFAF7; border: 1px solid #E3DFD5; font-variant-numeric: tabular-nums; }
  th, td { text-align: left; vertical-align: top; padding: 8px 10px; border-top: 1px solid #E3DFD5; }
  th { font-size: 10px; text-transform: uppercase; letter-spacing: .12em; color: #9C9891; font-weight: 600; }
  td ul { margin: 0; padding-left: 16px; font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 11px; color: #6B6862; }
  .dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 6px; }
  .none { color: #9C9891; }
  details { margin-top: 6px; } summary { cursor: pointer; color: #6B6862; font-size: 12px; }
  details ol { padding-left: 18px; font-size: 12px; }
</style>
<div class="wrap">
<p class="eyebrow">Generated from the matrix</p>
<h1>Delivery matrix</h1>
<p class="muted">${esc(c.says)} Each group names the agent that builds it. The live picture is <a href="/map">/map</a>.</p>`)

  for (const l1 of MATRIX) {
    out.push(`<h2>${esc(l1.code)} · ${esc(l1.stream)}</h2>\n<p class="muted">${esc(l1.blurb)}</p>`)
    for (const g of l1.groups) {
      out.push(`<h3>${esc(g.code)} · ${esc(g.name)} <span class="muted">— ${esc(agentOf.get(g.domain) ?? g.domain)}</span></h3>`)
      out.push('<table>\n<tr><th>Code</th><th>Process</th><th>Status</th><th>Owner</th><th>Files</th><th>Tests</th></tr>')
      for (const p of g.processes) {
        out.push(
          `<tr id="${esc(p.code)}"><td>${esc(p.code)}</td>` +
          `<td>${esc(p.name)}<details><summary>${p.tasks.length} tasks</summary><ol>${p.tasks.map((t) => `<li>${esc(t)}</li>`).join('')}</ol></details></td>` +
          `<td><span class="dot" style="background:${COLOR[p.status]}"></span>${WORD[p.status]}</td>` +
          `<td>${esc(p.owner)}</td>` +
          `<td>${list(p.implementedBy ?? [], 'None named')}</td>` +
          `<td>${list(p.testedBy ?? [], 'None named')}</td></tr>`
        )
      }
      out.push('</table>')
    }
  }
  out.push('</div>\n</html>\n')
  return out.join('\n')
}
