/**
 * The delivery matrix, as data.
 *
 * ── Why this is code and not a document ──────────────────────────────
 *
 * It was an HTML page, and within two agent runs it was wrong: accounts
 * receivable still read "not started" after it had been built and tested,
 * and the outbound screening pack had no row at all. Nobody noticed,
 * because a page cannot notice.
 *
 * This codebase has a rule about that, learned the expensive way with the
 * positioning of the home page: **a page describing what is true is wrong
 * within a month; a test is wrong for exactly one commit.**
 *
 * So the matrix is data, and `__tests__/invariants/matrix.test.ts` checks
 * the claims it makes:
 *
 *   · an L3 claiming BUILT must name files, and they must exist;
 *   · an L3 claiming BUILT must name tests, and they must exist;
 *   · every L2 an agent domain claims to answer for must be here;
 *   · every L3 must have an owner who is a real agent.
 *
 * That last set is what makes "update the matrix" a step rather than an
 * intention. An agent that builds something and does not record it here
 * breaks the build, on its own commit, while it is still the cheapest
 * moment to fix.
 *
 * ── What the levels mean ─────────────────────────────────────────────
 *
 * L1 — the value stream. L2 — the process group. L3 — the process, which
 * has an owner and a service level. L4 — the task somebody or something
 * actually picks up.
 */

import type { DomainKey } from '@/lib/domains'

export type Status =
  /** Exists, has tests, and there is a screen somebody can click. */
  | 'BUILT'
  /** The arithmetic or the model is there and something downstream is not. */
  | 'PARTIAL'
  /** Written down, nothing coded. */
  | 'SPEC'
  | 'NONE'

export interface L3 {
  code: string
  name: string
  /** What somebody actually does. */
  tasks: string[]
  /** The role that owns the process, not the agent that codes it. */
  owner: string
  status: Status
  /** Repo-relative paths. Required where status is BUILT or PARTIAL. */
  implementedBy?: string[]
  /** Repo-relative test paths. Required where status is BUILT. */
  testedBy?: string[]
}

export interface L2 {
  code: string
  name: string
  /** The domain whose agent codes this group. */
  domain: DomainKey
  processes: L3[]
}

export interface L1 {
  code: string
  stream: string
  blurb: string
  groups: L2[]
}

const B = 'BUILT' as const
const P = 'PARTIAL' as const
const S = 'SPEC' as const
const N = 'NONE' as const

export const MATRIX: L1[] = [
  {
    code: 'L1.1', stream: 'Source to contract',
    blurb: 'From somebody needing a person to somebody being chosen.',
    groups: [
      { code: 'L2.1.1', name: 'Demand intake', domain: 'DEMAND', processes: [
        { code: 'L3.1.1.1', name: 'Requisition raise and approve', owner: 'Hiring manager', status: B,
          tasks: ['Draft the role', 'Owner and raiser', 'Three desks: HR reads the role, Procurement audits the suppliers, the lead signs the money',
            'Alongside at one rank, the lead after both', 'Auto-clear inside policy, by name, with the reason', 'Nobody signs their own',
            'Procurement names the suppliers; the release stays within them', 'Published · Cancelled · Archived',
            'The chain read by desk, on the list, the row and the raise form', 'Words change freely; money goes back through approval',
            'Words change on one that is out, and every supplier who received it is told', 'The panel, and a discussion on the row'],
          implementedBy: [
            'src/lib/requisition-approval.ts', 'src/lib/requisition-stage.ts', 'src/lib/requisition-change.ts',
            'src/app/api/requisitions/route.ts', 'src/app/api/requisitions/[id]/route.ts',
            'src/app/api/requisitions/[id]/approve/route.ts',
            'src/app/api/requisitions/[id]/distribute/route.ts', 'src/app/api/settings/approval-rules/route.ts',
            'src/app/api/program/team/route.ts',
            'src/app/dashboard/requisitions/page.tsx', 'src/app/dashboard/requisitions/[id]/page.tsx',
            'src/app/dashboard/requisitions/chain.tsx', 'src/app/dashboard/program/team/page.tsx',
          ],
          testedBy: [
            '__tests__/invariants/requisition-approval.test.ts', '__tests__/invariants/requisition-stage.test.ts',
            '__tests__/invariants/requisition-change.test.ts', '__tests__/invariants/requisition-chain-screens.test.ts',
            '__tests__/invariants/requisition-change-screens.test.ts',
            '__integration__/client-programme.test.ts',
          ] },
        { code: 'L3.1.1.2', name: 'Budget and rate band', owner: 'Program manager', status: B,
          tasks: ['Check the cost object has money', 'Set the band per invitation'],
          implementedBy: ['src/lib/contract-rate.ts', 'src/lib/invitation-visibility.ts'],
          testedBy: ['__tests__/invariants/contract-rate.test.ts', '__tests__/invariants/invitation-visibility.test.ts'] },
        { code: 'L3.1.1.3', name: 'Supplier release', owner: 'Program manager', status: B,
          tasks: ['Choose who sees it', 'Stagger by tier', 'Set the response window'],
          implementedBy: ['src/app/api/requisitions/[id]/distribute/route.ts', 'src/lib/invitation-visibility.ts'],
          testedBy: ['__tests__/invariants/invitation-visibility.test.ts'] },
      ]},
      { code: 'L2.1.2', name: 'Supply response', domain: 'SUPPLY', processes: [
        { code: 'L3.1.2.1', name: 'Bench matching', owner: 'Recruiter', status: B,
          tasks: ['Rules filter first', 'One model pass on what survives', 'Factors, basis, confidence, unknowns',
            'The row says whether a model or arithmetic scored it, read from the agent-run ledger and never inferred from the basis sentence'],
          implementedBy: ['src/lib/match-engine.ts', 'src/lib/bench-filter.ts', 'src/lib/candidate-fit.ts',
            'src/app/api/requirements/[id]/matches/route.ts'],
          testedBy: ['__tests__/invariants/match-engine.test.ts', '__tests__/invariants/bench-filter.test.ts', '__tests__/invariants/candidate-fit.test.ts',
            '__tests__/invariants/match-decided-by.test.ts'] },
        { code: 'L3.1.2.2', name: 'Submission assembly', owner: 'Recruiter', status: B,
          tasks: ['Point-in-time CV', 'Rate and availability', 'Batch with per-item errors',
            'An employer puts its own W2 forward with no listing; the employee is told'],
          implementedBy: ['src/lib/resumes.ts', 'src/app/api/submissions/route.ts',
            'src/app/api/submissions/kind.ts', 'src/app/api/submissions/own-people/route.ts'],
          testedBy: ['__tests__/invariants/submission.test.ts', '__tests__/invariants/resumes.test.ts',
            '__integration__/internal-submission.test.ts'] },
        { code: 'L3.1.2.3', name: 'Right to represent', owner: 'Recruiter', status: B,
          tasks: ['Take the hold', 'Refuse a duplicate at source', 'Release on award'],
          implementedBy: ['src/lib/representation.ts', 'src/lib/holds.ts'],
          testedBy: ['__tests__/invariants/representation.test.ts'] },
      ]},
      { code: 'L2.1.4', name: 'Reaching the market, and moving work between firms', domain: 'MARKET', processes: [
        { code: 'L3.1.4.1', name: 'What we say we are', owner: 'Etyme', status: B,
          tasks: [
            'Category before cleverness, the way Concur says travel and expense',
            'Never one module describing itself',
            'Never lead with AI, and never claim we place anybody',
            'The terms, the privacy notice and the DPA are reachable from the footer, and no price is on the page',
            'No real company is named on the page, or on the demo the page hands a visitor to, or in the seeds behind it',
          ],
          implementedBy: ['src/lib/positioning.ts', 'src/app/page.tsx',
            'src/app/demo/seats.ts', 'src/app/demo/page.tsx'],
          testedBy: ['__tests__/invariants/positioning.test.ts', '__tests__/invariants/demo-names.test.ts'] },
        { code: 'L3.1.4.2', name: 'A requirement going down a chain', owner: 'Account manager', status: B,
          tasks: [
            'The end client described, not named, where the agreement forbids it',
            'The band travels, the sender’s own rate never does',
            'A blind key so two rivals find a collision without naming the chain',
          ],
          implementedBy: ['src/lib/distribution.ts'],
          testedBy: ['__tests__/invariants/distribution.test.ts'] },
        { code: 'L3.1.4.3', name: 'A consultant going up a chain', owner: 'Bench operator', status: B,
          tasks: [
            'Unnamed until a right to represent is on file',
            'Current employer withheld, because naming it identifies them anyway',
            'Nothing sent at all rather than a full CV where no redacted one exists',
          ],
          implementedBy: ['src/lib/distribution.ts'],
          testedBy: ['__tests__/invariants/distribution.test.ts'] },
        { code: 'L3.1.4.4', name: 'The disclosure record', owner: 'Compliance', status: B,
          tasks: [
            'What was sent, to whom, under which agreement',
            'What was withheld, and the reason in the words you would use',
            'Says where the chain leaves the platform and the guarantee stops',
          ],
          implementedBy: ['src/lib/distribution.ts'],
          testedBy: ['__tests__/invariants/distribution.test.ts'] },
        { code: 'L3.1.4.5', name: 'Lead capture and nurture', owner: 'Etyme', status: B,
          tasks: [
            'Only people who asked to hear from us — no consent, no row',
            'A purchased list is refused whole, so it cannot be laundered by mixing',
            'Cold outbound at volume trains a market to filter you',
          ],
          implementedBy: [
            'src/lib/public-site/leads.ts',
            'src/app/api/market/leads/route.ts',
            'src/app/site/ask.tsx',
            'src/app/page.tsx',
          ],
          testedBy: ['__tests__/invariants/marketing-leads.test.ts'] },
      ]},
      { code: 'L2.1.3', name: 'Evaluation', domain: 'DEMAND', processes: [
        { code: 'L3.1.3.1', name: 'Screening loop', owner: 'Client screener', status: B,
          tasks: ['Nine rule checks', 'Attempt cap and fix list', 'Human sample review'],
          implementedBy: ['src/lib/screening.ts', 'src/lib/checks.ts', 'src/lib/loop.ts'],
          testedBy: ['__tests__/invariants/screening.test.ts', '__tests__/invariants/checks.test.ts', '__tests__/invariants/loop.test.ts'] },
        { code: 'L3.1.3.2', name: 'Interview', owner: 'Hiring manager', status: B,
          tasks: ['Three-party acceptance', 'Chase after 24 hours', 'Flag a fourth round',
            'Propose a round from the candidate', 'Rounds in turn', 'Tell all three', 'The candidate answers'],
          implementedBy: [
            'src/lib/interviews.ts', 'src/lib/interview-proposal.ts', 'src/lib/interview-notices.ts',
            'src/components/propose-interview.tsx',
            'src/app/api/submissions/[id]/interviews/route.ts', 'src/app/api/interviews/[id]/route.ts',
            'src/app/api/me/interviews/[id]/respond/route.ts', 'src/app/api/me/pipeline/route.ts',
            'src/app/dashboard/submissions/page.tsx', 'src/app/dashboard/interviews/page.tsx',
            'src/app/dashboard/my-work/page.tsx',
          ],
          testedBy: [
            '__tests__/invariants/interviews.test.ts', '__tests__/invariants/interview-proposal.test.ts',
            '__tests__/invariants/interview-notices.test.ts', '__tests__/invariants/interview-conversation.test.ts',
            '__tests__/invariants/client-interviews.test.ts', '__tests__/invariants/my-work-interviews.test.ts',
            '__tests__/invariants/interview-desks.test.ts', '__integration__/interview-rounds.test.ts',
          ] },
        { code: 'L3.1.3.4', name: 'Talking to a supplier', owner: 'Hiring manager', status: B,
          tasks: ['Demand opens, supply answers', 'Only a firm on the deal', 'From the role or the candidate',
            'The other side is told', 'Own notes never leave the company'],
          implementedBy: [
            'src/lib/threads.ts', 'src/lib/thread-notices.ts', 'src/components/thread.tsx',
            'src/app/api/conversations/route.ts', 'src/app/api/conversations/messages/route.ts',
            'src/app/dashboard/requisitions/[id]/page.tsx', 'src/app/dashboard/submissions/page.tsx',
            'src/app/dashboard/conversations/page.tsx',
          ],
          testedBy: [
            '__tests__/invariants/threads.test.ts', '__tests__/invariants/thread-screens.test.ts',
            '__integration__/supplier-thread.test.ts',
          ] },
        { code: 'L3.1.3.3', name: 'Award and seat close', owner: 'Program manager', status: B,
          tasks: ['Governance checks', 'Seat arithmetic', 'Raise both sides of the deal', 'Stand down the rest'],
          implementedBy: ['src/lib/award.ts', 'src/app/api/submissions/[id]/award/route.ts'],
          testedBy: ['__tests__/invariants/award.test.ts'] },
      ]},
    ],
  },
  {
    code: 'L1.2', stream: 'Contract to onboard',
    blurb: 'Papering the deal, clearing the person, getting them on site. Onboarding lives here — five times.',
    groups: [
      { code: 'L2.2.1', name: 'Commercial papering', domain: 'DEMAND', processes: [
        { code: 'L3.2.1.1', name: 'Master agreement and SOW', owner: 'Account manager', status: P,
          tasks: ['Terms, margin floor, payment days — warns with a reason code, never blocks',
            'A statement of work cannot be signed before anybody wrote what the work is',
            'A client reading the same agreement never sees the vendor’s floor',
            'Payment days say what they run from — receipt of the invoice, the invoice date, the end of the work period or approval — and an agreement written before anybody asked keeps counting from the period end',
            'An early-payment discount is as many rungs as were agreed, each a number of days and a rate, and an order may override the agreement’s',
            'An agreement has a term: the day it starts, the day it runs out, and whether it rolls on, renews itself or simply stops — and one nobody gave a term says so rather than looking like it runs forever',
            'An agreement has a standing that can be ended, with a reason, so its capacity and its margin floor stop enforcing when somebody tears it up',
            'A signature is a named person with a title on a named side, and an agreement is executed only when both sides have signed — one signature says which side still owes a counter-signature',
            'The executed document is a file on the record with a hash, not an attachment in somebody’s email — recorded and attested, never verified by us and never sent for e-signature',
            'Every change writes what the terms were before it, who made it and why, so \u201cwhat were the payment days on 3 March\u201d has an answer',
            'Only the desk that owns prices may change payment days, the margin floor or the term, and the refusal says who to ask',
            'The nightly job marks an agreement running out or run out, rolls the ones whose own paper says they renew, and tells the contracting desk at ninety, sixty and thirty days and once when it has lapsed'],
          implementedBy: [
            'src/app/api/program/agreements/verdict.ts',
            'src/app/api/program/agreements/route.ts',
            'src/app/api/program/agreements/trail.ts',
            'src/app/api/program/agreements/[id]/route.ts',
            'src/app/api/program/agreements/[id]/sign/route.ts',
            'src/app/api/program/agreements/[id]/end/route.ts',
            'src/app/api/program/agreements/[id]/history/route.ts',
            'src/lib/agreement-term.ts',
            'src/app/api/cron/agreement-terms/route.ts',
            'src/lib/billing-cascade.ts',
            'src/app/api/program/engagements/[id]/sow/route.ts',
            'src/app/dashboard/program/agreements/page.tsx',
            'prisma/schema.prisma',
          ],
          testedBy: ['__tests__/invariants/agreements.test.ts', '__tests__/invariants/schema-terms.test.ts',
            '__tests__/invariants/early-payment.test.ts', '__tests__/invariants/agreement-term.test.ts',
            '__integration__/agreement-lifecycle.test.ts'] },
        { code: 'L3.2.1.2', name: 'Sell contract', owner: 'Account manager', status: B,
          tasks: ['Bill rate, term, end client', 'Cost object and PO attached at award'],
          implementedBy: ['src/app/api/submissions/[id]/award/route.ts', 'src/app/api/contracts/route.ts'],
          testedBy: ['__tests__/invariants/contracts.test.ts', '__tests__/invariants/award.test.ts'] },
        { code: 'L3.2.1.3', name: 'Buy contract or employment agreement', owner: 'Delivery manager', status: B,
          tasks: ['Pay model, share basis, burden', 'Raised at award, never after',
            'Carries what an overtime hour is worth to the worker, which is a different fact from what the client is billed for one — statute sets a floor and an employer may have agreed more',
            'Says what the net days on a vendor bill are counted from'],
          implementedBy: ['src/lib/award.ts', 'src/lib/pay-model.ts', 'prisma/schema.prisma',
            'src/lib/payroll-export.ts', 'src/lib/billing-cascade.ts', 'src/app/api/payroll/export/route.ts'],
          testedBy: ['__tests__/invariants/pay-model.test.ts', '__tests__/invariants/award.test.ts', '__tests__/invariants/schema-terms.test.ts',
            '__tests__/invariants/payroll-export.test.ts'] },
        { code: 'L3.2.1.4', name: 'The work order — one row, named per viewer', owner: 'Procurement', status: B,
          tasks: [
            'A client raises a purchase order; the supplier reads the same row as its sales order; the trade calls it a work order',
            'Issue to the sub-vendor',
            'Draw down and stop at the ceiling',
            'The ceiling, the four parties, the billing basis and its milestones on one row — an order carries a ceiling, a contract carries a rate',
            'Whether an unanswered timesheet counts as approved, and after how many working days — the client’s own term, read by the nightly job',
            'One order, a contract for each person on it',
            'Both numbers kept: the buyer’s PO number and the seller’s own order reference',
          ],
          implementedBy: [
            'src/lib/purchase-order.ts', 'src/lib/order-naming.ts', 'prisma/schema.prisma',
            'src/app/api/purchase-orders/route.ts', 'src/app/api/cron/auto-approve/route.ts',
            'src/app/api/program/milestones/route.ts',
          ],
          testedBy: [
            '__tests__/invariants/purchase-order.test.ts', '__tests__/invariants/work-order.test.ts',
            '__integration__/work-order.test.ts', '__integration__/full-spine.test.ts',
          ] },
      ]},
      { code: 'L2.2.2', name: 'Party onboarding — five processes, one word', domain: 'PLATFORM', processes: [
        { code: 'L3.2.2.1', name: 'Client onboarding', owner: 'Account manager', status: B,
          tasks: ['Sales handover as a derived checklist, never ticked boxes', 'Approval chain, cost objects, calendars', 'Every gap names why it matters and where to fix it'],
          implementedBy: ['src/lib/party-onboarding.ts', 'src/app/api/onboarding/readiness/route.ts', 'src/app/dashboard/onboarding/page.tsx'],
          testedBy: ['__tests__/invariants/party-onboarding.test.ts'] },
        { code: 'L3.2.2.2', name: 'Supplier onboarding', owner: 'Procurement', status: B,
          tasks: ['Due diligence and insurance, where nothing-on-file is missing, never fine', 'W-9 and where the money goes', 'Agreement on file before the first submission'],
          implementedBy: ['src/lib/party-onboarding.ts', 'src/lib/packets.ts', 'src/app/api/onboarding/readiness/route.ts'],
          testedBy: ['__tests__/invariants/party-onboarding.test.ts', '__tests__/invariants/packets.test.ts'] },
        { code: 'L3.2.2.3', name: 'Consultant onboarding', owner: 'Delivery manager', status: B,
          tasks: ['Profile, and the consent that is theirs alone', 'Engagement papers and the pay model agreed', 'Documents at award, never at application'],
          implementedBy: ['src/lib/party-onboarding.ts', 'src/app/api/onboarding/readiness/route.ts'],
          testedBy: ['__tests__/invariants/party-onboarding.test.ts'] },
        { code: 'L3.2.2.4', name: 'Assignment onboarding', owner: 'Hiring manager', status: B,
          tasks: ['Start confirmed by a person — the fact every invoice stands on', 'Compliance cleared before day one', 'First timesheet in, because the habit is set in week one', 'Somebody else in the seat'],
          implementedBy: ['src/lib/party-onboarding.ts', 'src/app/api/onboarding/confirm-start/route.ts', 'src/app/dashboard/onboarding/page.tsx', 'src/lib/replacement.ts', 'src/app/api/placements/[id]/replace/route.ts'],
          testedBy: ['__tests__/invariants/party-onboarding.test.ts', '__tests__/invariants/replacement.test.ts', '__integration__/money-moves.test.ts'] },
        { code: 'L3.2.2.6', name: 'Counterparty register', owner: 'Account manager', status: B,
          tasks: [
            'Who we work with and as what — client, supplier, prime, MSP',
            'Derived from agreements, plus prospects no paper covers yet',
            'Nothing removable while contracts or invoices are live between you',
          ],
          implementedBy: ['src/lib/counterparty.ts', 'src/app/api/counterparties/route.ts', 'src/app/dashboard/contacts/page.tsx'],
          testedBy: ['__tests__/invariants/counterparty.test.ts'] },
        { code: 'L3.2.2.7', name: 'Contact book', owner: 'Account manager', status: B,
          tasks: [
            'Who at each counterparty to call, and about what',
            'Duplicates refused on email or phone, never merged on a name',
            'Links to a real account when the contact joins, instead of drifting beside it',
          ],
          implementedBy: ['src/lib/contacts.ts', 'src/app/api/contacts/route.ts', 'src/app/dashboard/contacts/page.tsx'],
          testedBy: ['__tests__/invariants/contacts.test.ts'] },
        { code: 'L3.2.2.8', name: 'The demo door', owner: 'Etyme', status: B,
          tasks: [
            'Pick the desk that is yours, rather than classify yourself into a kind of firm',
            'Every door on the page opens on a seeded company of the kind its words claim',
            'No real company is named on a door, or in any seed a door reads',
            'Seeding the world again on a later day makes no second copy of anything and no error',
            'Every seeded company holds a domain nobody can register, so a real sign-in is never seated at a demo tenant',
            'A door for the person, not only for the firm: four consultants in four industries, each landing on their own work and never on a company dashboard',
            'One of the four is not IT staffing — a travel nurse on three twelve-hour shifts, paid corp to corp through the company she owns, with a state license that runs out inside the assignment',
            'A program office that sells to its client and buys below it, including its own W2 employee with no bench listing and no purchase order',
            'Both halves of a supplying firm’s book are named on its door: what it sells upward and what it owes downward',
            'Every table in the schema either carries seeded rows or is named, in one place, as written only when somebody acts — and the list fails when it goes stale in either direction',
            'The layers above and below a placement are seeded too: the order that authorized the spend and its ceiling, the project that accumulates it, the books it posts to, and the AP run that settles it',
            'What a firm can prove is seeded with the file behind it, the edition of the form that was signed, and the evidence an I-9 was completed from — a form with nothing behind it is not held',
            'Every seeded firm keeps a calendar, so a due date is generated against real days off rather than against weekends alone',
            'Every cycle date in a seeded world comes out of the one generator, including the demo consultant’s, so no placement anywhere has dates the calendar setting cannot reach',
            'A match score in the seed comes out of the match engine and carries its factors, basis, confidence and unknowns — never a number written by hand',
          ],
          implementedBy: [
            'src/app/demo/seats.ts', 'src/app/demo/page.tsx', 'src/app/demo/desk-picker.tsx',
            'src/app/api/demo/route.ts', 'src/app/api/seed-world/route.ts', 'src/lib/demo-session.ts',
            'src/lib/seed-world.ts', 'src/lib/seed-programmes.ts', 'src/lib/seed-doors.ts', 'src/lib/seed-days.ts',
            'src/lib/seed-calendar.ts', 'src/lib/seed-standing.ts', 'src/lib/seed-order-to-cash.ts',
            'src/lib/seed-pipeline.ts', 'src/lib/demo-seed-consultant.ts',
          ],
          testedBy: [
            '__integration__/demo-seats.test.ts', '__integration__/reseed-gate.test.ts',
            '__integration__/reseed-across-days.test.ts', '__tests__/invariants/demo-names.test.ts',
            '__integration__/seed-covers-the-matrix.test.ts',
          ] },
        { code: 'L3.2.2.9', name: 'A counterparty that is not on the system', owner: 'Account manager', status: B,
          tasks: [
            'A firm on the register that has not taken possession of itself — it can be named, sent a role and scored; it cannot sign in and the network cannot see it',
            'A client lists a supplier that is not here, and a supplier lists a client that is not here — the same door, both ways round',
            'A firm already here under its own domain is never copied; the refusal says to ask them instead',
            'A claimed firm may write an order naming a shell on either leg, including the leg where it is not the natural issuer — so a supplier can record the purchase order its client handed it',
            'A firm cannot name a company that is already here as its counterparty without them',
            'The row says which of the two parties typed it in',
            'Every row already points at the company id, so it is the claimant’s the instant they take possession',
          ],
          implementedBy: [
            'src/lib/off-system.ts', 'src/app/api/clients/route.ts', 'src/app/api/suppliers/route.ts',
            'src/app/api/contracts/route.ts', 'src/app/api/purchase-orders/route.ts',
            'src/app/api/claim/[token]/route.ts',
          ],
          testedBy: [
            '__tests__/invariants/work-order.test.ts', '__integration__/work-order.test.ts',
            '__integration__/supplier-onboarding.test.ts',
          ] },
        { code: 'L3.2.2.10', name: 'The company\u2019s own calendar', owner: 'Program office', status: B,
          tasks: [
            'A company adds its own days off, or seeds a country\u2019s public holidays for a year in one click',
            'A holiday marked for one country does not move another site\u2019s dates',
            'Which way a date moves off a weekend or a holiday is the company\u2019s to set \u2014 the working day before, the working day after, or left where it falls',
            'Asked once for hours, once for pay and once for billing, because a firm that pays on the Friday before still bills on the Monday after',
            'Every company that has said nothing keeps the day it was already being paid on',
            'A direction the generator cannot read is refused at the door rather than written to the column',
            'Dates already generated keep their dates, and the screen says so rather than implying a change is backdated',
            'The direction a company set is the direction the generated date actually moves, on every placement, whoever wrote the cycles',
            'A company that changes the rule keeps every date it had already generated, and the months an extension adds are the only ones written',
            'A calendar is the company\u2019s own: nobody may add a day to another firm\u2019s or take one out of it, because a day on this calendar moves the pay day of everybody that firm pays',
            'Every seeded firm keeps one, so the setting can be walked on the demo rather than described',
          ],
          implementedBy: [
            'src/lib/cycle-shift.ts', 'src/lib/holidays.ts',
            'src/lib/cycle-generator.ts', 'src/lib/contract-cycles.ts',
            'src/app/api/contracts/route.ts', 'src/app/api/contracts/[id]/extend/route.ts',
            'src/app/api/settings/route.ts', 'src/app/api/settings/holidays/route.ts',
            'src/app/api/holidays/route.ts', 'src/app/api/holidays/who.ts',
            'src/lib/seed-calendar.ts',
            'src/app/dashboard/settings/page.tsx', 'prisma/schema.prisma',
          ],
          testedBy: [
            '__tests__/invariants/cycle-shift.test.ts',
            '__tests__/invariants/cycle-shift-reaches-the-dates.test.ts',
            '__tests__/invariants/holiday-calendar-is-yours.test.ts',
          ] },
        { code: 'L3.2.2.5', name: 'Tenant onboarding', owner: 'Etyme', status: B,
          tasks: ['Company formation and domain', 'Roles, seats, notification channel', 'Generated public site',
            'The desks that may award at a supplier are the ones that sell and the ones that decide who goes where \u2014 a prime is both sell and buy, and the account manager who sold the person awards them',
            'The desk that papers an award does not choose who gets it, and the recruiter who submitted somebody does not hand them the job',
            'A permission the defaults grew after a company was formed reaches it the next time somebody opens users and permissions, and nothing is ever taken off a role the company narrowed itself'],
          implementedBy: ['src/lib/onboarding.ts', 'src/lib/company-defaults.ts', 'src/lib/company-roles.ts', 'src/lib/public-site.ts'],
          testedBy: ['__tests__/invariants/onboarding.test.ts', '__tests__/invariants/company-defaults.test.ts',
            '__tests__/invariants/award-desks.test.ts'] },
      ]},
      { code: 'L2.2.3', name: 'Compliance clearance', domain: 'REGULATORY', processes: [
        { code: 'L3.2.3.1', name: 'Work authorization', owner: 'Compliance', status: B,
          tasks: ['Visa class and expiry', 'Petition and transfer events', 'Blocks, never warns', 'A petition from filing to running out'],
          implementedBy: ['src/lib/document-stages.ts', 'src/app/api/cron/visa-watch/route.ts', 'src/lib/visa-petition.ts', 'src/app/api/compliance/petitions/route.ts'],
          testedBy: ['__tests__/invariants/document-stages.test.ts', '__tests__/invariants/visa-petition.test.ts', '__integration__/visa-petition.test.ts'] },
        { code: 'L3.2.3.2', name: 'What may be asked, and when', owner: 'Compliance', status: B,
          tasks: ['Questions at application, documents at award', 'Per-jurisdiction rule table', 'Moves an item rather than dropping it'],
          implementedBy: ['src/lib/document-stages.ts', 'src/lib/packets.ts', 'src/lib/packet-derivation.ts'],
          testedBy: ['__tests__/invariants/document-stages.test.ts', '__tests__/invariants/packets.test.ts'] },
        { code: 'L3.2.3.3', name: 'Insurance and indemnity', owner: 'Compliance', status: B,
          tasks: ['Certificate on file and in date', 'A lapse blocks; an absence chases — which cover is required is the client’s rule',
            'Cover that has not begun blocks the same as cover that ran out — and a renewal filed early does not block the firm that filed it',
            'Every desk reads the day cover begins, not only the day it ends — the compliance page, the packet, the submission door, the outbound pack, the nightly chase and the placement thread',
            'The weeks between one policy ending and the next beginning are chased, and the supplier is asked for cover for them rather than told to renew what it has already sent',
            'A sub-vendor’s cover on a placement answers with a computed standing rather than the status somebody typed when they filed it \u2014 and the thread prints the computed word, in the compliance page’s own vocabulary, with the sentence on the hover',
            'The verdict on the firm below a supplier \u2014 whether it could put anybody forward today, and what to do where it could not \u2014 is on the placement thread, in the words the submission door computed'],
          implementedBy: ['src/lib/packets.ts', 'src/lib/document-stages.ts', 'src/lib/document-type.ts',
            'src/lib/outbound-pack.ts', 'src/lib/cover-gap.ts',
            'src/app/api/compliance/route.ts', 'src/app/dashboard/compliance/page.tsx',
            'src/app/api/outbound-pack/own-documents.ts', 'src/app/api/packets/route.ts',
            'src/app/api/cron/watch/route.ts', 'src/app/api/placements/[id]/route.ts',
            'src/app/dashboard/placements/[id]/page.tsx', 'src/components/cover-standing.tsx'],
          testedBy: ['__tests__/invariants/supplier-cover.test.ts', '__tests__/invariants/packets.test.ts',
            '__tests__/invariants/document-type.test.ts', '__tests__/invariants/document-floor.test.ts',
            '__tests__/invariants/cover-gap.test.ts',
            '__tests__/components/placement-cover.test.ts',
            '__integration__/document-floor.test.ts', '__integration__/cover-chase.test.ts'] },
        { code: 'L3.2.3.6', name: 'What kind of thing a document is', owner: 'Compliance', status: B,
          tasks: [
            'Three purposes, and the purpose is the behavior — compliance is watched, an agreement is signed, proof stands behind something else',
            'Three validity shapes — never expires, runs out, covers a period — and the start of the period is read',
            'The list is the company’s: a type it invents behaves from the first document filed against it, with no migration',
            'A form has an edition, and an edition the issuer had already replaced is an audit finding rather than a bar to work',
            'A form is not evidence on its own — an I-9 records what somebody looked at, and what they looked at is recorded',
          ],
          implementedBy: ['src/lib/document-type.ts', 'src/app/api/document-types/route.ts',
            'src/lib/contract-clearance.ts', 'src/lib/document-stages.ts', 'src/lib/packets.ts',
            // What we send out about ourselves reads the same window: a
            // policy beginning in October is never sent to a client as
            // proof of cover in September.
            'src/lib/outbound-pack.ts', 'src/app/api/outbound-pack/own-documents.ts'],
          testedBy: ['__tests__/invariants/document-type.test.ts', '__integration__/document-type.test.ts',
            '__tests__/invariants/document-floor.test.ts', '__integration__/document-floor.test.ts'] },
        { code: 'L3.2.3.4', name: 'Attestation of a check', owner: 'Compliance', status: B,
          tasks: ['Records that a check happened, never a verdict', 'Says no on statutory checks however fresh', 'Counts how many firms hold a copy', 'Asked for, sent, uploaded, signed'],
          implementedBy: ['src/lib/attestation.ts', 'src/lib/document-request.ts', 'src/app/dashboard/documents/page.tsx', 'src/app/api/me/papers/route.ts'],
          testedBy: ['__tests__/invariants/attestation.test.ts', '__tests__/invariants/document-request.test.ts', '__integration__/paperwork.test.ts'] },
        { code: 'L3.2.3.7', name: 'A license to practice', owner: 'Compliance', status: B,
          tasks: [
            'A lapsed state license blocks the start, and the refusal names the license, its number and the state that issued it',
            'A license whose period has not begun licenses nobody, and blocks the same way',
            'A license in date today that runs out inside the assignment warns with the days counted rather than refusing work the law permits',
            'Which roles need one is read off the role title, and a role no regulator licenses is asked for nothing',
            'A licensed role with no license on file at all is refused — at activation, on the placement thread, and in the client’s starting-soon preview',
            'Which types count as a license is the company’s own dictionary: compliance purpose, blocks on lapse, supplied by the candidate',
            'The nightly chase asks the person sixty days ahead, through the firm that places them, with the board named and the link theirs',
            'A license already renewed is not asked for twice, and the ask on a seeded seat is one the chase raised rather than one the seed typed',
          ],
          implementedBy: ['src/lib/document-stages.ts', 'src/lib/contract-clearance.ts', 'src/lib/packets.ts',
            'src/lib/credential-chase.ts', 'src/app/api/cron/watch/route.ts',
            'src/app/api/contracts/[id]/activate/route.ts', 'src/app/api/placements/[id]/route.ts',
            'src/app/api/program/route.ts', 'src/app/api/compliance/route.ts', 'src/lib/seed-doors.ts'],
          testedBy: ['__tests__/invariants/professional-license.test.ts', '__tests__/invariants/credential-chase.test.ts',
            '__integration__/licensed-practice.test.ts', '__integration__/credential-renewal.test.ts',
            '__integration__/licensed-start.test.ts'] },
        { code: 'L3.2.3.5', name: 'Being screened — the outbound pack', owner: 'Compliance', status: B,
          tasks: ['Assemble our own documents for a client', 'Refuse anything expired, with no force flag', 'Readiness before a bid'],
          implementedBy: ['src/lib/outbound-pack.ts', 'src/app/api/outbound-pack/route.ts', 'src/app/dashboard/outbound-pack/page.tsx'],
          testedBy: ['__tests__/invariants/outbound-pack.test.ts'] },
      ]},
    ],
  },
  {
    code: 'L1.3', stream: 'Work to approve',
    blurb: 'Hours are a fact. Approvals are opinions about that fact.',
    groups: [
      { code: 'L2.3.1', name: 'Capture', domain: 'DEMAND', processes: [
        { code: 'L3.3.1.1', name: 'Time capture', owner: 'Consultant', status: B,
          tasks: ['Daily entry against the assignment', 'Overtime and on-call as elements',
            'A week over the line is worth nothing extra until whoever signs it says so \u2014 the usual rate, a premium, or time off in the bank',
            'Banked hours are a ledger, and a draw cannot take more than is there',
            'Leave taken never counts toward the weekly threshold',
            'In a chain the answer is written against the leg the decider buys on \u2014 the client at the top, a prime on the contract it buys from its sub, the employer on the leg the hours sit on',
            'The seeded client desk holds one week over the line that nobody has priced, so all three answers can be walked'],
          implementedBy: ['src/lib/work-ledger.ts', 'src/lib/timesheet-authority.ts',
            'src/lib/overtime.ts', 'src/lib/time-off.ts',
            'src/app/api/timesheets/[id]/approve/route.ts', 'src/app/dashboard/timesheets/page.tsx',
            'src/lib/seed-programmes.ts'],
          testedBy: ['__tests__/invariants/work-ledger.test.ts', '__tests__/invariants/timesheet-authority.test.ts',
            '__tests__/invariants/overtime.test.ts', '__tests__/invariants/time-off.test.ts',
            '__tests__/invariants/overtime-approval.test.ts',
            '__tests__/invariants/seed-overtime.test.ts'] },
        { code: 'L3.3.1.2', name: 'Expense capture', owner: 'Consultant', status: B,
          tasks: ['Receipt, policy check, staleness', 'Billable versus absorbed', 'Rides on the next invoice', 'Paid when the invoice is paid'],
          implementedBy: ['src/lib/expense-approval.ts', 'src/lib/expense-billing.ts',
            'src/app/api/expenses/actions/route.ts'],
          testedBy: ['__tests__/invariants/expense-approval.test.ts', '__tests__/invariants/expense-billing.test.ts',
            '__tests__/invariants/money-automation-names.test.ts', '__integration__/status-ledger.test.ts'] },
        { code: 'L3.3.1.3', name: 'Milestone capture', owner: 'Delivery manager', status: B,
          tasks: ['Deliverable submitted for acceptance',
            'Client accepts, or rejects with a reason code from a closed list',
            'Acceptance is what makes it billable, asserted by the same function the invoice run uses',
            'The delivery-to-acceptance gap in days, from real delivery dates', 'Bills on acceptance'],
          implementedBy: [
            'src/lib/billing-plan.ts',
            'src/app/api/program/milestones/acceptance.ts',
            'src/app/api/program/milestones/route.ts',
            'src/app/dashboard/program/milestones/page.tsx', 'src/lib/three-way-match.ts'],
          testedBy: ['__tests__/invariants/milestone-acceptance.test.ts', '__tests__/invariants/money-moves.test.ts', '__integration__/money-moves.test.ts'] },
      ]},
      { code: 'L2.3.2', name: 'Approval', domain: 'CONVERSATION', processes: [
        { code: 'L3.3.2.1', name: 'Client approval', owner: 'Hiring manager', status: B,
          tasks: ['One assertion per party, per date range', 'Partial approval is ordinary',
            'A week coming due is put in front of both signatures \u2014 the client that received the work and the employer that pays for it \u2014 and never in front of the person whose hours they are'],
          implementedBy: ['src/lib/work-ledger.ts', 'src/app/api/timesheets/[id]/assert/route.ts',
            'src/app/api/cron/due-cycles/route.ts', 'src/lib/due-cycle-desks.ts'],
          testedBy: ['__tests__/invariants/work-ledger.test.ts', '__tests__/invariants/due-cycles-desks.test.ts'] },
        { code: 'L3.3.2.2', name: 'Employer acceptance', owner: 'Delivery manager', status: B,
          tasks: ['Accepts the basis for pay', 'A different number needs a reason'],
          implementedBy: ['src/lib/work-ledger.ts', 'src/lib/timesheet-signatures.ts'],
          testedBy: ['__tests__/invariants/timesheet-signatures.test.ts'] },
        { code: 'L3.3.2.3', name: 'Auto-approval', owner: 'Rules', status: B,
          tasks: ['Window per contract', 'Anomaly holds it back'],
          implementedBy: ['src/lib/auto-approval.ts'],
          testedBy: ['__tests__/invariants/auto-approval.test.ts'] },
        { code: 'L3.3.2.4', name: 'Reversal and correction', owner: 'Payroll', status: B,
          tasks: ['Supersede, never edit', 'Posts to the month it belonged to'],
          implementedBy: ['src/lib/timesheet-reversal.ts'],
          testedBy: ['__tests__/invariants/timesheet-reversal.test.ts'] },
      ]},
    ],
  },
  {
    code: 'L1.4', stream: 'Approve to invoice',
    blurb: 'Order to cash. Earning, invoicing and collecting are three separate facts.',
    groups: [
      { code: 'L2.4.1', name: 'Billing', domain: 'MONEY', processes: [
        { code: 'L3.4.1.1', name: 'Invoice generation', owner: 'AR clerk', status: B,
          tasks: ['From approvals, not a rate card', 'Cycle, straddle and holiday calendar',
            'A week over the line bills what whoever signed it decided \u2014 never what the contract offered',
            'An hour nobody has decided is not billed at any price, and the invoice says how many it left off',
            'A decision that has reached an invoice is stamped billed, and billed cannot be changed',
            'A line prints the working that adds up to it, and never a multiplication that does not come out',
            'The due date counts from what the contract says it counts from, so an invoice raised six days after the period ends is not claimed overdue six days early',
            'The day the client received it is recorded, because that is the day a net-30 clock actually starts, and a due date anchored on a receipt nobody confirmed says so rather than guessing',
            'Nothing schedules a due date in advance: the invoice carries its own, so no second answer is generated on the calendar to disagree with it',
            'The day a bill is to be raised is put in front of accounts receivable a week out, in their own words, and never in front of the contractor it is about'],
          implementedBy: ['src/lib/invoice-loop.ts', 'src/lib/periods.ts', 'src/lib/cycle-generator.ts',
            'src/lib/cycle-kinds.ts', 'src/lib/template-packs.ts', 'scripts/retire-due-cycles.mjs',
            'src/app/api/cron/due-cycles/route.ts', 'src/lib/due-cycle-desks.ts',
            'src/app/api/invoices/generate/route.ts', 'scripts/backfill-overtime-decisions.ts',
            'src/app/api/invoices/[id]/route.ts', 'src/app/api/invoices/[id]/payments/route.ts',
            'src/app/dashboard/invoices/[id]/page.tsx',
            'prisma/schema.prisma'],
          testedBy: ['__tests__/invariants/invoice-loop.test.ts', '__tests__/invariants/periods.test.ts',
            '__tests__/invariants/cycles.test.ts', '__tests__/invariants/invoice-overtime.test.ts',
            '__tests__/invariants/due-dates-belong-to-the-document.test.ts',
            '__tests__/invariants/cycle-kinds.test.ts', '__tests__/invariants/cycle-complete.test.ts',
            '__integration__/premium-invoice.test.ts', '__tests__/invariants/schema-terms.test.ts',
            '__tests__/invariants/due-cycles-desks.test.ts'] },
        { code: 'L3.4.1.2', name: 'Partner functions', owner: 'AR clerk', status: B,
          tasks: ['Sold-to, bill-to, ship-to, payer', 'Consolidated billing refuses to mix bill-tos, payers or currencies', 'Self-billing flagged'],
          implementedBy: ['src/lib/billing-cascade.ts', 'src/app/api/invoices/generate/route.ts'],
          testedBy: ['__tests__/invariants/partner-functions.test.ts', '__tests__/invariants/billing-cascade.test.ts'] },
        { code: 'L3.4.1.3', name: 'Tax determination', owner: 'Controller', status: B,
          tasks: ['Place of supply and rate, as a rule table', 'Withholding where it applies', 'Refuses rather than guesses where the place of supply is unknowable', 'The rate and outcome are queryable columns, not a JSON blob'],
          implementedBy: ['src/lib/billing-cascade.ts', 'src/app/api/invoices/generate/route.ts'],
          testedBy: ['__tests__/invariants/tax-determination.test.ts'] },
      ]},
      { code: 'L2.4.2', name: 'Accounts receivable', domain: 'MONEY', processes: [
        { code: 'L3.4.2.1', name: 'AR aging and dunning', owner: 'AR clerk', status: B,
          tasks: ['Buckets from the due date, not the invoice date', 'Four letters and then a person', 'One letter per customer, not per invoice'],
          implementedBy: ['src/lib/ar-ageing.ts', 'src/app/api/ar/route.ts',
            'src/app/api/ar/book.ts', 'src/app/api/ar/dunning/route.ts',
            'src/app/dashboard/ar/page.tsx'],
          testedBy: ['__tests__/invariants/ar-ageing.test.ts'] },
        { code: 'L3.4.2.2', name: 'Cash application', owner: 'AR clerk', status: B,
          tasks: ['Match receipts to invoices', 'Short pays are a dispute, not arrears', 'Unapplied cash queue — money you have and cannot count'],
          implementedBy: ['src/lib/ar-ageing.ts', 'src/app/api/ar/payments/route.ts',
            'src/app/api/ar/route.ts', 'src/app/api/ar/book.ts', 'src/app/dashboard/ar/page.tsx'],
          testedBy: ['__tests__/invariants/cash-application.test.ts', '__tests__/invariants/ar-ageing.test.ts'] },
        { code: 'L3.4.2.3', name: 'Disputes and credit notes', owner: 'Account manager', status: B,
          tasks: ['Reason coded, not free text', 'Credit note reverses in period', 'The book ages net of applied credits'],
          implementedBy: ['src/lib/ar-ageing.ts', 'src/lib/gl.ts', 'src/app/api/ar/credit-notes/route.ts',
            'src/app/api/ar/book.ts', 'src/app/dashboard/ar/page.tsx'],
          testedBy: ['__tests__/invariants/credit-notes.test.ts', '__tests__/invariants/gl.test.ts'] },
      ]},
      { code: 'L2.4.3', name: 'Credit management', domain: 'MONEY', processes: [
        { code: 'L3.4.3.1', name: 'Exposure, not a credit score', owner: 'Controller', status: B,
          tasks: ['Unpaid plus unbilled plus committed, less cash held', 'Open-ended assignments held outside the headline'],
          implementedBy: ['src/lib/credit.ts', 'src/app/api/ar/route.ts', 'src/app/dashboard/ar/page.tsx'],
          testedBy: ['__tests__/invariants/credit.test.ts'] },
        { code: 'L3.4.3.2', name: 'Limit and breach', owner: 'Controller', status: B,
          tasks: ['Limit per vendor and client pair', 'Warns, names an approver, demands a reason — never blocks'],
          implementedBy: ['src/lib/credit.ts', 'src/app/api/ar/credit-limit/route.ts'],
          testedBy: ['__tests__/invariants/credit.test.ts'] },
        { code: 'L3.4.3.3', name: 'Collections and escalation', owner: 'Controller', status: B,
          tasks: ['Owned, promised, broken, stop-work advised — the ladder beyond the letters', 'Factoring eligibility and reason-coded write-offs', 'A promise is a date and an amount, persisted, and a broken one counts toward stop-work'],
          implementedBy: ['src/lib/ar-ageing.ts', 'src/app/api/ar/collections/route.ts',
            'src/app/dashboard/ar/page.tsx'],
          testedBy: ['__tests__/invariants/collections.test.ts',
            '__tests__/invariants/money-automation-names.test.ts'] },
      ]},
    ],
  },
  {
    code: 'L1.5', stream: 'Approve to pay',
    blurb: 'Procure to pay, and paying the person. What is owed and what is paid are two numbers.',
    groups: [
      { code: 'L2.5.1', name: 'Worker pay', domain: 'MONEY', processes: [
        { code: 'L3.5.1.1', name: 'Payroll instruction', owner: 'Payroll', status: B,
          tasks: ['Export to ADP, Paychex or a file', 'From acceptance, never from a rate card',
            'Pay day reaches the payroll desk a week out \u2014 the nightly scan read only the sell leg and so had never once surfaced one'],
          implementedBy: ['src/lib/payroll-export.ts', 'src/app/api/cron/due-cycles/route.ts', 'src/lib/due-cycle-desks.ts'],
          testedBy: ['__tests__/invariants/payroll-export.test.ts', '__tests__/invariants/due-cycles-desks.test.ts'] },
        { code: 'L3.5.1.2', name: 'Pay model application', owner: 'Payroll', status: B,
          tasks: ['Fixed, share of bill, share of margin', 'Working shown line by line', 'Commission run, under the cap'],
          implementedBy: ['src/lib/pay-model.ts', 'src/lib/commission.ts', 'src/app/api/payroll/commissions/route.ts'],
          testedBy: ['__tests__/invariants/pay-model.test.ts', '__tests__/invariants/commission.test.ts', '__integration__/money-moves.test.ts'] },
        { code: 'L3.5.1.3', name: 'Bench and reserve', owner: 'Payroll', status: B,
          tasks: ['Hold back, draw down, carry limit', 'What happens on exit, with the reason on record'],
          implementedBy: ['src/lib/bench-policy.ts', 'src/lib/order-postings.ts',
            'src/app/api/payroll/reserve/route.ts', 'src/app/dashboard/payroll/page.tsx'],
          testedBy: ['__tests__/invariants/bench-reserve.test.ts', '__tests__/invariants/bench-policy.test.ts',
            '__tests__/invariants/money-automation-names.test.ts'] },
        { code: 'L3.5.1.4', name: 'Off-cycle and corrections', owner: 'Payroll', status: B,
          tasks: ['Short pay carried, never a negative payslip', 'The carry derived from postings, never a stored running total', 'A carry column on the payroll screen, loaded on demand'],
          implementedBy: ['src/lib/pay-model.ts', 'src/app/api/payroll/off-cycle/route.ts'],
          testedBy: ['__tests__/invariants/pay-carry.test.ts', '__tests__/invariants/pay-model.test.ts'] },
      ]},
      { code: 'L2.5.2', name: 'Accounts payable', domain: 'MONEY', processes: [
        { code: 'L3.5.2.1', name: 'Vendor bill intake', owner: 'AP clerk', status: B,
          tasks: ['Bill against the PO and the approvals', 'Duplicate and over-bill refusal', 'A waivable failure is DISPUTED and out of every payment run until somebody records why',
            'When the bill falls due is the bill\u2019s own date, beside when it arrived and when it was paid \u2014 never a monthly cycle guessed before the bill existed',
            'The day a supplier\u2019s invoice is expected reaches accounts payable, and says record rather than raise, because the supplier issues it and we receive it'],
          implementedBy: ['src/lib/purchase-order.ts', 'src/app/api/ap/bills/route.ts',
            'src/lib/cycle-kinds.ts', 'src/app/dashboard/ap/page.tsx',
            'src/app/api/cron/due-cycles/route.ts', 'src/lib/due-cycle-desks.ts'],
          testedBy: ['__tests__/invariants/vendor-bill-match.test.ts', '__tests__/invariants/purchase-order.test.ts',
            '__tests__/invariants/due-dates-belong-to-the-document.test.ts',
            '__tests__/invariants/due-cycles-desks.test.ts'] },
        { code: 'L3.5.2.2', name: 'Three-way match', owner: 'AP clerk', status: B,
          tasks: ['PO, receipt of work, invoice', 'Tolerance and exception queue', 'Exceptions routed to the AP desk',
            'A premium somebody signed is read from the decision, not called bad arithmetic'],
          implementedBy: ['src/lib/three-way-match.ts', 'src/lib/invoice-match.ts', 'src/app/api/ap/bills/route.ts',
            'src/app/api/invoices/[id]/match/route.ts', 'src/app/dashboard/ap/page.tsx', 'src/app/api/decisions/route.ts'],
          testedBy: ['__tests__/invariants/three-way-match.test.ts', '__tests__/invariants/vendor-bill-match.test.ts',
            '__tests__/invariants/money-moves.test.ts', '__tests__/invariants/invoice-overtime.test.ts'] },
        { code: 'L3.5.2.3', name: 'Payment run and remittance', owner: 'AP clerk', status: B,
          tasks: ['Batch by terms and currency, never mixed', 'Approved by somebody other than the creator', 'Remittance advice naming the bills covered'],
          implementedBy: ['src/lib/ap-delay.ts', 'src/app/api/ap/payment-runs/route.ts',
            'src/app/dashboard/ap/page.tsx'],
          testedBy: ['__tests__/invariants/payment-run.test.ts'] },
        { code: 'L3.5.2.4', name: 'Chain payment behavior', owner: 'Controller', status: B,
          implementedBy: ['src/lib/ap-delay.ts', 'src/app/api/ap/route.ts',
            'src/app/api/ap/bills/route.ts', 'src/app/dashboard/ap/page.tsx'],
          testedBy: ['__tests__/invariants/ap-delay.test.ts'],
          tasks: [
            'Agreed terms against actual days, per party, both directions',
            'Chain float — who is financing whom, and for how many days',
            'Pay-when-paid detection, because that clause pushes the float down',
            'Say where the chain leaves the platform and the guarantee stops',
          ] },
      ]},
      { code: 'L2.5.3', name: 'Statutory', domain: 'MONEY', processes: [
        { code: 'L3.5.3.1', name: 'Payroll tax data for the bureau', owner: 'Payroll bureau', status: B,
          tasks: [
            'Etyme never files — the bureau does, and every screen says so',
            'Deposit schedule and deadline calendar from the lookback, shifted off non-business days',
            'Wage data from PAY postings, never from a rate card',
          ],
          implementedBy: ['src/lib/payroll-export.ts', 'src/app/api/payroll/statutory/route.ts',
            'src/app/dashboard/payroll/page.tsx'],
          testedBy: ['__tests__/invariants/statutory.test.ts'] },
        { code: 'L3.5.3.2', name: 'Worker tax document data', owner: 'Payroll bureau', status: B,
          tasks: [
            'Per-person per-year wage summaries: W-2 gross, 1099-NEC box 1',
            'A corporation gets no 1099-NEC for services, and it says why',
            'CSV a bureau ingests, marked prepared-not-filed',
          ],
          implementedBy: ['src/lib/payroll-export.ts', 'src/app/api/payroll/statutory/route.ts',
            'src/app/dashboard/payroll/page.tsx'],
          testedBy: ['__tests__/invariants/statutory.test.ts'] },
      ]},
    ],
  },
  {
    code: 'L1.6', stream: 'Record to report',
    blurb: 'The project order accumulates. The journal balances. Their ERP reads it in their own language.',
    groups: [
      { code: 'L2.6.1', name: 'The ledger', domain: 'MONEY', processes: [
        { code: 'L3.6.1.1', name: 'Journal and balance', owner: 'Controller', status: B,
          tasks: ['Debits equal credits before writing', 'One entry per source event'],
          implementedBy: ['src/lib/gl.ts'],
          testedBy: ['__tests__/invariants/gl.test.ts'] },
        { code: 'L3.6.1.2', name: 'The project order', owner: 'Controller', status: B,
          tasks: ['Collects revenue and cost for one piece of work', 'Allocations per head', 'Basis stated on every line'],
          implementedBy: ['src/lib/order.ts', 'src/lib/order-postings.ts'],
          testedBy: ['__tests__/invariants/order.test.ts'] },
        { code: 'L3.6.1.3', name: 'Settlement and close', owner: 'Controller', status: B,
          tasks: ['Balance out to the cost center, always in pairs', 'Settled orders refuse new postings'],
          implementedBy: ['src/lib/order.ts', 'src/lib/order-postings.ts',
            'src/app/api/profitability/settle/route.ts', 'src/app/dashboard/profitability/page.tsx'],
          testedBy: ['__tests__/invariants/settlement.test.ts', '__tests__/invariants/order.test.ts'] },
        { code: 'L3.6.1.4', name: 'Loose ends', owner: 'Controller', status: B,
          tasks: ['Seven kinds of broken link', 'Worst first, then oldest', 'Cold trails past ninety days'],
          implementedBy: ['src/lib/loose-ends.ts', 'src/app/api/loose-ends/route.ts', 'src/app/dashboard/loose-ends/page.tsx'],
          testedBy: ['__tests__/invariants/loose-ends.test.ts'] },
      ]},
      { code: 'L2.6.2', name: 'Profitability', domain: 'MONEY', processes: [
        { code: 'L3.6.2.1', name: 'By contract, person, customer, order', owner: 'Controller', status: B,
          tasks: ['Same postings, four questions', 'Refuses a margin with no cost behind it'],
          implementedBy: ['src/lib/profitability.ts', 'src/app/dashboard/profitability/page.tsx'],
          testedBy: ['__tests__/invariants/profitability.test.ts'] },
        { code: 'L3.6.2.2', name: 'Earned against cash', owner: 'Controller', status: B,
          tasks: ['To collect and still owed to people', 'Side by side, never merged'],
          implementedBy: ['src/lib/order.ts'],
          testedBy: ['__tests__/invariants/order.test.ts'] },
        { code: 'L3.6.2.3', name: 'Currency', owner: 'Controller', status: B,
          tasks: ['Converted once, rate stamped', 'Parallel valuation kept alongside', 'Two currencies in one total throws'],
          implementedBy: ['src/lib/order.ts', 'src/lib/order-postings.ts'],
          testedBy: ['__tests__/invariants/order.test.ts'] },
      ]},
      { code: 'L2.6.3', name: 'Integration', domain: 'PLATFORM', processes: [
        { code: 'L3.6.3.1', name: 'ERP account mapping', owner: 'Etyme', status: B,
          tasks: ['SAP and Oracle for clients', 'NetSuite and QuickBooks for vendors', 'CSV for the firm with no system'],
          implementedBy: ['src/lib/gl.ts', 'src/lib/erp-profiles.ts'],
          testedBy: ['__tests__/invariants/gl.test.ts', '__tests__/invariants/erp-profiles.test.ts'] },
        { code: 'L3.6.3.2', name: 'Outbound posting', owner: 'Etyme', status: B,
          tasks: ['Export once, stamped as sent — a re-export is a double posting', 'Refuses on an unmapped account rather than writing a suspense line'],
          implementedBy: ['src/lib/gl.ts', 'src/app/api/integrations/export/route.ts', 'src/app/dashboard/integrations/page.tsx'],
          testedBy: ['__tests__/invariants/gl.test.ts'] },
        { code: 'L3.6.3.3', name: 'Reconciliation', owner: 'Controller', status: B,
          tasks: ['Our balance against theirs, matched by reference then exact amount, never fuzzier', 'Every break named, and a difference the breaks do not explain refuses sign-off'],
          implementedBy: ['src/lib/reconciliation.ts', 'src/app/api/integrations/reconcile/route.ts', 'src/app/dashboard/integrations/page.tsx'],
          testedBy: ['__tests__/invariants/reconciliation.test.ts'] },
      ]},
    ],
  },
  {
    code: 'L1.7', stream: 'Govern and protect',
    blurb: 'The exposures nobody bills for. Block where legally grounded, warn and record a reason everywhere else.',
    groups: [
      { code: 'L2.7.1', name: 'Workforce risk', domain: 'REGULATORY', processes: [
        { code: 'L3.7.1.1', name: 'Tenure and co-employment', owner: 'Compliance', status: B,
          tasks: ['Aggregated across every supplier', 'Break in service and eligibility date'],
          implementedBy: ['src/app/api/tenure/route.ts', 'src/app/dashboard/tenure/page.tsx'],
          testedBy: ['__tests__/invariants/tenure.test.ts'] },
        { code: 'L3.7.1.2', name: 'Worker classification', owner: 'Compliance', status: B,
          tasks: ['Test the arrangement, not the label', 'Evidence kept FOR the position taken, re-derivable rather than trusted',
            'A position the test contradicts needs a written reason, because counsel may differ and silence may not',
            'Exempt status is the employer assertion and never Etyme judgment \u2014 the screen can rule an exemption out on arithmetic and has no verdict that means exempt',
            'A client overtime treatment is a billing fact on the sell leg and never reduces a nonexempt wage',
            'A week nobody has classified is left off the payroll file and named, never exported at whichever rate was handy',
            'An exemption asserted is a row keyed on the employment relationship, so the same person can be exempt at one employer and not at another, and two people on one contract can honestly differ',
            'The row keeps what the screen said at the time, so the position is re-derivable rather than trusted, and carries a date to remake it'],
          implementedBy: ['src/lib/worker-classification.ts',
            'src/app/api/compliance/classification/route.ts',
            'src/app/dashboard/compliance/page.tsx',
            'prisma/schema.prisma',
            'src/app/api/contracts/[id]/exempt/route.ts', 'src/lib/payroll-export.ts'],
          testedBy: ['__tests__/invariants/worker-classification.test.ts',
            '__tests__/invariants/classification-call.test.ts',
            '__tests__/invariants/exempt-status.test.ts',
            '__tests__/invariants/schema-terms.test.ts',
            '__tests__/invariants/payroll-export.test.ts'] },
        { code: 'L3.7.1.3', name: 'Governance and segregation of duties', owner: 'Compliance', status: B,
          tasks: ['Approver is not the beneficiary', 'Blocks, and says whose rule'],
          implementedBy: ['src/lib/governance.ts', 'src/lib/governance-authorship.ts'],
          testedBy: ['__tests__/invariants/governance.test.ts', '__tests__/invariants/governance-authorship.test.ts'] },
      ]},
      { code: 'L2.7.2', name: 'Commercial risk', domain: 'SUPPLY', processes: [
        { code: 'L3.7.2.1', name: 'Supplier financial risk', owner: 'Procurement', status: B,
          tasks: ['Insurance and payment behavior, where nothing-on-record is never clear',
            'A judgment with a date to remake it, and a sweep that flags the stale ones',
            'Warns and names who acts — a commercial judgment, never a block', 'A standing per supplier the rule reads'],
          implementedBy: ['src/lib/supplier-risk.ts', 'src/app/api/vendors/risk/route.ts',
            'src/app/dashboard/scorecards/page.tsx', 'src/lib/supplier-tier.ts'],
          testedBy: ['__tests__/invariants/supplier-risk.test.ts', '__tests__/invariants/standing-and-seats.test.ts', '__integration__/standing-and-seats.test.ts'] },
        { code: 'L3.7.2.2', name: 'Concentration risk', owner: 'Controller', status: B,
          tasks: ['One client, one supplier, one person — thresholds carrying their meaning in words',
            'A book too small to measure says so, rather than showing three clean ticks'],
          implementedBy: ['src/lib/concentration.ts', 'src/app/api/vendors/concentration/route.ts',
            'src/app/dashboard/scorecards/page.tsx'],
          testedBy: ['__tests__/invariants/concentration.test.ts'] },
        { code: 'L3.7.2.3', name: 'Bench burn', owner: 'Bench operator', status: B,
          tasks: ['What the gaps cost, daily, by tier', 'Profitable on paper only'],
          implementedBy: ['src/lib/bench-policy.ts', 'src/lib/profitability.ts'],
          testedBy: ['__tests__/invariants/bench-burn.test.ts', '__tests__/invariants/bench-policy.test.ts'] },
      ]},
      { code: 'L2.7.3', name: 'Data and access', domain: 'REGULATORY', processes: [
        { code: 'L3.7.3.1', name: 'Access log', owner: 'Etyme', status: B,
          tasks: ['Every read of another person, refusals too'],
          implementedBy: ['src/lib/access-log.ts'],
          testedBy: ['__tests__/invariants/access-grant.test.ts'] },
        { code: 'L3.7.3.2', name: 'Company walls', owner: 'Etyme', status: B,
          tasks: ['Filtered at the query, not the screen',
            'Which side of a deal the caller sits on is asked before the record is read, and a permission never stands in for it',
            'A client\'s copy of a placement carries no buy leg at all — the sub-vendor\'s name, that firm\'s cover, the pay days, the cost and the margin are not sent rather than not drawn',
            'The wall is asserted on what the route returns, never on what the screen renders',
            'A client sees the standing of the firm employing the person on its site, and not that firm\'s name, unless its agreement with the prime says otherwise',
            'Disclosure is a term on the master agreement between client and prime, off by default, amended on the version trail like every other term',
            'A withheld name says which firm it comes through, never a blank and never a dash',
            'The same rule answers for names that lib/chain-top answers for rates, in one function the three client-facing surfaces share',
            'A sweep over source names every client-facing read that prints a firm below the rung the client pays, or the file sits on a list with its owner and what it leaks',
            'Every read the sweep named is closed and its list is empty: the "needs you" queue, identity resolution, the register, one person\'s page, the approval queue and the reasoning panel all ask the name rule rather than the selling firm',
            'A client that opens a rung its own supplier arranged reads no name, no rate and no invoice from it, and is told why',
            'The disclosure term has a control on the agreements screen, so a client that demanded it at signing is not recorded by hand through the API',
            'An ask for a person opens a thread with the rung the client pays, and disclosure grants a name and never a channel'],
          implementedBy: ['src/lib/walls.ts', 'src/lib/account-walls.ts', 'src/lib/seat.ts',
            'src/lib/chain-top.ts', 'src/app/api/people/[id]/ask/route.ts',
            'src/lib/resolve-client-company.ts', 'src/app/api/placements/[id]/route.ts',
            'src/lib/chain-names.ts', 'src/app/api/compliance/route.ts',
            'src/app/api/tenure/route.ts', 'src/app/api/alumni/route.ts',
            'src/app/api/program/agreements/[id]/route.ts',
            'src/app/dashboard/program/agreements/page.tsx',
            'src/app/dashboard/program/agreements/standing.ts',
            'src/app/api/decisions/route.ts', 'src/app/api/identity/route.ts',
            'src/app/api/people/route.ts', 'src/app/api/people/[id]/route.ts',
            'src/app/api/program/route.ts', 'src/app/api/why/[type]/[id]/route.ts'],
          testedBy: ['__tests__/invariants/walls.test.ts', '__tests__/invariants/seat.test.ts',
            '__tests__/invariants/chain-names.test.ts',
            '__tests__/invariants/client-facing-names.test.ts',
            '__tests__/invariants/agreement-screen.test.ts',
            '__tests__/invariants/ask-routing.test.ts',
            '__integration__/ask-for-person.test.ts',
            '__integration__/placement-payload.test.ts', '__integration__/full-spine.test.ts'] },
        { code: 'L3.7.3.3', name: 'What the system does on its own', owner: 'Etyme', status: B,
          tasks: ['Every action written to the automation log is named as unprompted, enforcement, or an act a person took',
            'Anything the system does unprompted carries a level from L0 Observe to L5 Fully autonomous',
            'A refusal aimed at somebody who asked for something carries no autonomy level',
            'Every scheduled job is named at the level it actually acts at',
            'A row says whether a rule or a model decided it, and says it does not know rather than guessing',
            'A new automated action with no level fails the build on the commit that adds it',
            'Every action name is written out in full, because a name assembled at runtime is one no reader and no check can find',
            'How many actions there are of each kind is counted from the ladder, never written into the sentence beside it'],
          implementedBy: ['src/lib/autonomy.ts', 'src/app/api/automation/route.ts', 'src/app/dashboard/automation/page.tsx',
            'src/app/api/requirements/[id]/matches/route.ts', 'src/app/api/cron/proactive-match/route.ts',
            'src/app/api/access/[contextId]/route.ts', 'src/app/api/ar/collections/route.ts',
            'src/app/api/contracts/[id]/activate/route.ts', 'src/app/api/expenses/actions/route.ts',
            'src/app/api/payroll/reserve/route.ts', 'src/app/api/holidays/route.ts'],
          testedBy: ['__tests__/invariants/autonomy.test.ts',
            '__tests__/invariants/access-lifecycle-log.test.ts',
            '__tests__/invariants/money-automation-names.test.ts',
            '__tests__/invariants/holiday-calendar-is-yours.test.ts'] },
        { code: 'L3.7.3.4', name: 'What we tell people about their data', owner: 'Compliance', status: B,
          tasks: ['Terms, a privacy notice and a DPA as ordinary pages, in the product\'s own look',
            'Every sentence derived from the schema and the code paths, and checked by a test against the file that proves it',
            'Two populations described as two relationships — a business user through a corporate tenant, a candidate with their own email',
            'Controller or processor left open for counsel rather than decided quietly, with the facts set out both ways',
            'Sub-processors listed from what the code actually calls, and the keys that reach nobody named too',
            'Where a candidate\'s name and the text of their CV reach a model, said exactly, with the arithmetic fallback said as precisely',
            'No retention period stated, because none is implemented; what happens today is stated instead',
            'Ten questions a lawyer must answer, on the page rather than in a comment',
            'A security posture for a client\'s review whose gap list is as specific as its control list'],
          implementedBy: ['src/lib/legal.ts', 'src/app/legal/document.tsx',
            'src/app/terms/page.tsx', 'src/app/privacy/page.tsx', 'src/app/dpa/page.tsx',
            'docs/security-posture.md'],
          testedBy: ['__tests__/invariants/legal-pages.test.ts'] },
        { code: 'L3.7.3.5', name: 'Whose rate is on the row', owner: 'Etyme', status: B,
          tasks: [
            'A rate is a term of a contract, and only its two parties may read it, each on their own side',
            'The site the work happens at is not a party to the money, however many rungs name it',
            'The person named on a sell contract is the subject of it, not a party to it',
            'In a chain the client is priced at the rung it pays, never the one underneath',
            'A refusal quotes the rate of the leg the reader is on',
            'A payroll file pays what somebody agreed to pay, never what somebody agreed to charge',
            'A rate band lives on the invitation, where only its recipient can read it',
            'Which scope each route may use is a register; an unregistered route fails the build',
            'Every scanner is run against the defect verbatim, so a guard cannot pass by describing the code',
            'Four of the same shape are named with their owner rather than left silent; a fifth fails the build'],
          implementedBy: [
            'src/lib/resolve-client-company.ts', 'src/lib/chain-top.ts', 'src/lib/payroll-export.ts',
            'src/app/api/timesheets/route.ts', 'src/app/api/timesheets/[id]/approve/route.ts',
            'src/app/api/payroll/export/route.ts', 'src/app/api/me/work/route.ts'],
          testedBy: [
            '__tests__/invariants/rate-party.test.ts', '__tests__/invariants/whose-rate.test.ts',
            '__integration__/whose-rate.test.ts'] },
      ]},
    ],
  },
]

// ── Reading it ────────────────────────────────────────────────────────

export function allProcesses(): { l1: L1; l2: L2; l3: L3 }[] {
  return MATRIX.flatMap((l1) =>
    l1.groups.flatMap((l2) => l2.processes.map((l3) => ({ l1, l2, l3 })))
  )
}

export function groupsFor(domain: DomainKey): L2[] {
  return MATRIX.flatMap((l1) => l1.groups).filter((g) => g.domain === domain)
}

export interface Coverage {
  total: number
  built: number
  partial: number
  spec: number
  none: number
  says: string
}

export function coverage(domain?: DomainKey): Coverage {
  const rows = allProcesses().filter((r) => !domain || r.l2.domain === domain)
  const by = (s: Status) => rows.filter((r) => r.l3.status === s).length

  return {
    total: rows.length,
    built: by('BUILT'),
    partial: by('PARTIAL'),
    spec: by('SPEC'),
    none: by('NONE'),
    says:
      `${by('BUILT')} of ${rows.length} processes built, ${by('PARTIAL')} partial, ` +
      `${by('SPEC') + by('NONE')} not started.`,
  }
}
