import type { FlowDiagram } from '@/lib/flows.generated'

/**
 * One stream, drawn.
 *
 * The drawing is wide because it is the real operating model rather than a
 * simplification, so it scrolls sideways in its own container and never makes
 * the page scroll. The numbered list under it is the readable version: the
 * same stations, in the same order, in the words the people at them use.
 *
 * The SVG string is generated by docs/lanes/public.mjs from docs/lanes/
 * streams.mjs and committed. It is never user input, and the leak guard in
 * __tests__/invariants/flows-public.test.ts runs over it on every build.
 */
export function FlowDrawing({ d }: { d: FlowDiagram }) {
  return (
    <section
      id={d.code.toLowerCase().replace(/[^a-z0-9]/g, '')}
      className="scroll-mt-6 border-t border-etyme-rule pt-10"
    >
      <p className="font-mono text-[11px] uppercase tracking-[0.12em] text-etyme-faint">
        {d.code}
      </p>
      <h2 className="mt-2 max-w-[24ch] text-balance font-serif text-[26px] leading-tight text-etyme-ink md:text-[32px]">
        {d.name}
      </h2>

      <figure className="mt-6">
        <div
          className="overflow-x-auto rounded-xl border border-etyme-rule bg-etyme-surface p-3"
          role="group"
          aria-label={`${d.name}: drawing, scrolls sideways`}
          tabIndex={0}
        >
          {/* eslint-disable-next-line react/no-danger */}
          <div className="text-etyme-ink" dangerouslySetInnerHTML={{ __html: d.svg }} />
        </div>
        <p className="mt-2 font-mono text-[11px] uppercase tracking-[0.08em] text-etyme-faint">
          Scrolls sideways, or read the stations below
        </p>
        <figcaption className="mt-3 max-w-[76ch] text-[14.5px] leading-relaxed text-etyme-muted">
          {d.caption}
        </figcaption>
      </figure>

      <ol className="mt-8 grid gap-px overflow-hidden rounded-xl border border-etyme-rule bg-etyme-rule md:grid-cols-2">
        {d.stations.map((s) => (
          <li key={s.n} className="bg-etyme-raised px-5 py-4">
            <div className="flex gap-3">
              <span className="mt-[3px] font-mono text-[11px] tabular-nums text-etyme-faint">
                {String(s.n).padStart(2, '0')}
              </span>
              <div>
                <p className="text-[15px] font-semibold leading-snug text-etyme-ink">
                  {s.label}
                  {s.pending ? (
                    <span className="ml-2 font-mono text-[10.5px] font-normal uppercase tracking-[0.08em] text-etyme-faint">
                      not built yet
                    </span>
                  ) : null}
                </p>
                {s.note ? (
                  <p className="mt-1 text-[13.5px] leading-relaxed text-etyme-muted">{s.note}</p>
                ) : null}
                {s.refuse ? (
                  <p className="mt-1.5 flex items-start gap-2 text-[13.5px] leading-relaxed text-etyme-attention">
                    <span className="evidence-dot evidence-dot--blocked mt-[7px]" aria-hidden="true" />
                    {s.refuse}
                  </p>
                ) : null}
              </div>
            </div>
          </li>
        ))}
      </ol>
    </section>
  )
}
